"""v3_hierarchy_batch_unit

Revision ID: 3f59f1647ba9
Revises: 693f01694db5
Create Date: 2026-06-20 19:59:10.622936
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f59f1647ba9'
down_revision: Union[str, None] = '693f01694db5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('program', sa.String(length=120), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=40), nullable=True),
    sa.Column('roster', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batches_teacher_id'), 'batches', ['teacher_id'], unique=False)
    op.create_table('units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_units_course_id'), 'units', ['course_id'], unique=False)
    op.add_column('commands', sa.Column('tokens_used', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('courses', sa.Column('batch_id', sa.UUID(), nullable=False))
    op.add_column('courses', sa.Column('professor', sa.String(length=160), nullable=False, server_default=''))
    op.add_column('courses', sa.Column('cover', sa.String(length=40), nullable=False, server_default=''))
    op.add_column('courses', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('courses', sa.Column('end_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_courses_batch_id'), 'courses', ['batch_id'], unique=False)
    op.create_foreign_key(None, 'courses', 'batches', ['batch_id'], ['id'], ondelete='CASCADE')
    op.drop_column('courses', 'roster')
    op.add_column('sessions', sa.Column('unit_id', sa.UUID(), nullable=True))
    op.drop_index('ix_sessions_course_id', table_name='sessions')
    op.create_index(op.f('ix_sessions_unit_id'), 'sessions', ['unit_id'], unique=False)
    op.drop_constraint('sessions_course_id_fkey', 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'units', ['unit_id'], ['id'], ondelete='CASCADE')
    op.drop_column('sessions', 'course_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('course_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key('sessions_course_id_fkey', 'sessions', 'courses', ['course_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_sessions_unit_id'), table_name='sessions')
    op.create_index('ix_sessions_course_id', 'sessions', ['course_id'], unique=False)
    op.drop_column('sessions', 'unit_id')
    op.add_column('courses', sa.Column('roster', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_index(op.f('ix_courses_batch_id'), table_name='courses')
    op.drop_column('courses', 'end_date')
    op.drop_column('courses', 'start_date')
    op.drop_column('courses', 'cover')
    op.drop_column('courses', 'professor')
    op.drop_column('courses', 'batch_id')
    op.drop_column('commands', 'tokens_used')
    op.drop_index(op.f('ix_units_course_id'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_batches_teacher_id'), table_name='batches')
    op.drop_table('batches')
    # ### end Alembic commands ###
