"""v5_department_semester

Revision ID: 3ff850cef37e
Revises: cf23a3739db7
Create Date: 2026-06-20 22:26:24.499789
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ff850cef37e'
down_revision: Union[str, None] = 'cf23a3739db7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_batch_id'), 'departments', ['batch_id'], unique=False)
    op.create_table('semesters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semesters_department_id'), 'semesters', ['department_id'], unique=False)
    op.create_table('semester_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('semester_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('semester_id', 'user_id', name='uq_semester_member')
    )
    op.create_index(op.f('ix_semester_members_semester_id'), 'semester_members', ['semester_id'], unique=False)
    op.create_index(op.f('ix_semester_members_user_id'), 'semester_members', ['user_id'], unique=False)
    op.drop_index('ix_batch_members_batch_id', table_name='batch_members')
    op.drop_index('ix_batch_members_user_id', table_name='batch_members')
    op.drop_table('batch_members')
    op.add_column('batches', sa.Column('start_year', sa.Integer(), nullable=False))
    op.add_column('batches', sa.Column('end_year', sa.Integer(), nullable=False))
    op.drop_column('batches', 'program')
    op.drop_column('batches', 'semester')
    op.drop_column('batches', 'section')
    op.drop_column('batches', 'year')
    op.drop_column('batches', 'roster')
    op.add_column('courses', sa.Column('semester_id', sa.UUID(), nullable=False))
    op.drop_index('ix_courses_batch_id', table_name='courses')
    op.create_index(op.f('ix_courses_semester_id'), 'courses', ['semester_id'], unique=False)
    op.drop_constraint('courses_batch_id_fkey', 'courses', type_='foreignkey')
    op.create_foreign_key(None, 'courses', 'semesters', ['semester_id'], ['id'], ondelete='CASCADE')
    op.drop_column('courses', 'batch_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('batch_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_foreign_key('courses_batch_id_fkey', 'courses', 'batches', ['batch_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_courses_semester_id'), table_name='courses')
    op.create_index('ix_courses_batch_id', 'courses', ['batch_id'], unique=False)
    op.drop_column('courses', 'semester_id')
    op.add_column('batches', sa.Column('roster', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('batches', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('batches', sa.Column('section', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column('batches', sa.Column('semester', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('batches', sa.Column('program', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_column('batches', 'end_year')
    op.drop_column('batches', 'start_year')
    op.create_table('batch_members',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('batch_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name='batch_members_batch_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='batch_members_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='batch_members_pkey'),
    sa.UniqueConstraint('batch_id', 'user_id', name='uq_batch_member')
    )
    op.create_index('ix_batch_members_user_id', 'batch_members', ['user_id'], unique=False)
    op.create_index('ix_batch_members_batch_id', 'batch_members', ['batch_id'], unique=False)
    op.drop_index(op.f('ix_semester_members_user_id'), table_name='semester_members')
    op.drop_index(op.f('ix_semester_members_semester_id'), table_name='semester_members')
    op.drop_table('semester_members')
    op.drop_index(op.f('ix_semesters_department_id'), table_name='semesters')
    op.drop_table('semesters')
    op.drop_index(op.f('ix_departments_batch_id'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
