"""session_join_code

Revision ID: 4f0b82dc8a31
Revises: b008194525b8
Create Date: 2026-06-20 17:39:35.162108
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f0b82dc8a31'
down_revision: Union[str, None] = 'b008194525b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add nullable first, backfill existing rows with unique codes, then enforce.
    op.add_column('sessions', sa.Column('join_code', sa.String(length=12), nullable=True))

    from app.models.session import generate_join_code

    conn = op.get_bind()
    rows = conn.execute(sa.text("SELECT id FROM sessions WHERE join_code IS NULL")).fetchall()
    used: set[str] = set()
    for (sid,) in rows:
        code = generate_join_code()
        while code in used:
            code = generate_join_code()
        used.add(code)
        conn.execute(
            sa.text("UPDATE sessions SET join_code = :c WHERE id = :id"),
            {"c": code, "id": sid},
        )

    op.alter_column('sessions', 'join_code', nullable=False)
    op.create_index(op.f('ix_sessions_join_code'), 'sessions', ['join_code'], unique=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_join_code'), table_name='sessions')
    op.drop_column('sessions', 'join_code')
    # ### end Alembic commands ###
