"""transcript_starred

Revision ID: 68f86c7e69b9
Revises: 4319f8e0168c
Create Date: 2026-06-20 18:21:40.771034
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68f86c7e69b9'
down_revision: Union[str, None] = '4319f8e0168c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'transcripts',
        sa.Column('starred', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcripts', 'starred')
    # ### end Alembic commands ###
