"""session_language

Revision ID: 693f01694db5
Revises: 68f86c7e69b9
Create Date: 2026-06-20 18:30:25.867724
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '693f01694db5'
down_revision: Union[str, None] = '68f86c7e69b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'sessions',
        sa.Column('language', sa.String(length=40), nullable=False, server_default='English'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'language')
    # ### end Alembic commands ###
