"""p4 whiteboard_logs

Revision ID: 6df6e14b360f
Revises: 5ed24f1197dc
Create Date: 2026-06-15 11:22:06.426554
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6df6e14b360f'
down_revision: Union[str, None] = '5ed24f1197dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whiteboard_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('tldraw_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('image_data', sa.Text(), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whiteboard_logs_session_id'), 'whiteboard_logs', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whiteboard_logs_session_id'), table_name='whiteboard_logs')
    op.drop_table('whiteboard_logs')
    # ### end Alembic commands ###
