"""p5 commands and quizzes

Revision ID: 8fbc91134019
Revises: 6df6e14b360f
Create Date: 2026-06-15 11:47:43.897679
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8fbc91134019'
down_revision: Union[str, None] = '6df6e14b360f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commands',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('raw_command', sa.Text(), nullable=False),
    sa.Column('intent', sa.Enum('GENERATE_QUIZ', 'SUMMARIZE', 'EXPLAIN', 'GENERATE_EXAMPLE', 'GENERATE_DIAGRAM', 'ANSWER_QUESTION', 'FORMAT_BOARD', 'OTHER', name='command_intent'), nullable=False),
    sa.Column('llm_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='command_status'), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commands_session_id'), 'commands', ['session_id'], unique=False)
    op.create_table('quizzes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('command_id', sa.UUID(), nullable=True),
    sa.Column('share_code', sa.String(length=32), nullable=False),
    sa.Column('quiz_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quizzes_session_id'), 'quizzes', ['session_id'], unique=False)
    op.create_index(op.f('ix_quizzes_share_code'), 'quizzes', ['share_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quizzes_share_code'), table_name='quizzes')
    op.drop_index(op.f('ix_quizzes_session_id'), table_name='quizzes')
    op.drop_table('quizzes')
    op.drop_index(op.f('ix_commands_session_id'), table_name='commands')
    op.drop_table('commands')
    # ### end Alembic commands ###
