"""rbac_batch_members

Revision ID: cf23a3739db7
Revises: 3f59f1647ba9
Create Date: 2026-06-20 21:32:17.375260
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf23a3739db7'
down_revision: Union[str, None] = '3f59f1647ba9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'user_id', name='uq_batch_member')
    )
    op.create_index(op.f('ix_batch_members_batch_id'), 'batch_members', ['batch_id'], unique=False)
    op.create_index(op.f('ix_batch_members_user_id'), 'batch_members', ['user_id'], unique=False)
    op.add_column('batches', sa.Column('created_by', sa.UUID(), nullable=False))
    op.drop_index('ix_batches_teacher_id', table_name='batches')
    op.create_index(op.f('ix_batches_created_by'), 'batches', ['created_by'], unique=False)
    op.drop_constraint('batches_teacher_id_fkey', 'batches', type_='foreignkey')
    op.create_foreign_key(None, 'batches', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.drop_column('batches', 'teacher_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('teacher_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'batches', type_='foreignkey')
    op.create_foreign_key('batches_teacher_id_fkey', 'batches', 'users', ['teacher_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_batches_created_by'), table_name='batches')
    op.create_index('ix_batches_teacher_id', 'batches', ['teacher_id'], unique=False)
    op.drop_column('batches', 'created_by')
    op.drop_index(op.f('ix_batch_members_user_id'), table_name='batch_members')
    op.drop_index(op.f('ix_batch_members_batch_id'), table_name='batch_members')
    op.drop_table('batch_members')
    # ### end Alembic commands ###
